import 'package:flutter/material.dart';
import 'package:flutter_localization/flutter_localization.dart';

mixin AppLocale {
  static const String nav1 = 'nav1';
  static const String nav2 = 'nav2';
  static const String nav3 = 'nav3';
  static const String role1 = 'role1';
  static const String role2 = 'role2';
  static const String moto1 = 'moto1';
  static const String moto2 = 'moto2';
  static const String moto3 = 'moto3';
  static const String badge1 = 'badge1';
  static const String badge2 = 'badge2';
  static const String badge3 = 'badge3';
  static const String introduction1 = 'introduction1';
  static const String introduction2 = 'introduction2';
  static const String highlight1= 'highlight1';
  static const String highlight2= 'highlight2';
  static const String highlight3= 'highlight3';
  static const String highlight4= 'highlight4';
  static const String highlight5= 'highlight5';
  static const String highlight6= 'highlight6';
  static const String experience1 = 'experience1';
  static const String experience2 = 'experience2';
  static const String experience3 = 'experience3';
  static const String experience4 = 'experience4';
  static const String project1 = 'project1';
  static const String project2 = 'project2';
  static const String achievement= 'achievement';
  static const String footer1 = 'footer1';
  static const String footer2 = 'footer2';
  static const String footer3 = 'footer3';

  static const Map<String, dynamic> EN = {
    nav1: 'About',
    nav2: 'Projects',
    nav3: 'Certifications',
    role1: 'Multi-Platform Developer',
    role2: 'IT Support Specialist',
    moto1: 'Services',
    moto2: 'I empower seamless, cross-platform solutions and offer top-notch IT support for a connected world.',
    moto3: 'Show more',
    badge1: 'Years of Experience',
    badge2: 'Projects',
    badge3: 'Certificates',
    introduction1: "I've been deeply immersed in the world of technology as an IT Support professional. Over four years, I've meticulously managed ",
    highlight1: "IT infrastructure",
    introduction2: ", ensured software and hardware are up-to-date, and provided responsive ",
    highlight2: "helpdesk support.",
    experience1: "Meticulous computer assembly, troubleshooting hardware and software issues, OS installation, and configuring required applications. Additionally, it includes setting up local area networks (LAN) for seamless connectivity in the company's work environment.",
    experience2: "Teach programming fundamentals using C++ to first-grade students, introduce Java-based object-oriented programming concepts to second graders, and cover advanced Java topics with a focus on MySQL database integration for third graders.",
    experience3: "Managed IT infrastructure maintenance, created pharmaceutical running-text advertisements with Arduino-configured LED modules, and developed pharmaceutical applications using Visual Basic .NET with features such as inventory and sales management.",
    experience4: "Planning and executing technology infrastructure procurement, managing budgets, IT asset management, configuring secure Mikrotik-based networks, performing OS and hardware installations.",
    project1: "Rhealth application is designed to provide customers with easy access to their medication information by using QR codes generated by pharmacy administrators.",
    project2: "Rsite is a website application designed to introduce myself. With a modern user interface, you can customize the primary color, switch between light and dark modes, and change the language.",
    achievement: "verify",
    footer1: "Design by Me",
    footer2: "Build with Flutter ",
    footer3: " using Material 3 and Provider.",
  };
  static const Map<String, dynamic> ID = {
    nav1: 'Tentang',
    nav2: 'Proyek',
    nav3: 'Sertifikasi',
    role1: 'Pengembang Multi-Platform',
    role2: 'Spesialis Dukungan TI',
    moto1: 'Layanan',
    moto2: 'Saya memberdayakan solusi lintas platform yang mulus dan menawarkan dukungan TI terbaik untuk dunia yang terhubung.',
    moto3: 'Tampilkan lebih banyak',
    badge1: 'Tahun Pengalaman',
    badge2: 'Proyek',
    badge3: 'Sertifikat',
    introduction1: "Saya telah tenggelam dalam dunia teknologi sebagai profesional Dukungan TI. Selama empat tahun, saya dengan teliti mengelola ",
    highlight1: "infrastruktur TI",
    introduction2: ", memastikan perangkat lunak dan perangkat keras tetap terkini, dan memberikan ",
    highlight2: "dukungan helpdesk yang responsif.",
    experience1: "Perakitan komputer yang teliti, pemecahan masalah perangkat keras dan perangkat lunak, instalasi sistem operasi, dan konfigurasi aplikasi yang diperlukan. Selain itu, termasuk pengaturan jaringan area lokal (LAN) untuk konektivitas yang mulus di lingkungan kerja perusahaan.",
    experience2: "Mengajar dasar-dasar pemrograman menggunakan C++ kepada siswa kelas satu, memperkenalkan konsep pemrograman berbasis objek Java kepada siswa kelas dua, dan membahas topik Java yang lebih lanjut dengan fokus pada integrasi basis data MySQL untuk siswa kelas tiga.",
    experience3: "Mengelola pemeliharaan infrastruktur TI, membuat iklan tekstual berjalan farmasi dengan modul LED yang dikonfigurasi Arduino, dan mengembangkan aplikasi farmasi menggunakan Visual Basic .NET dengan fitur seperti manajemen inventaris dan penjualan.",
    experience4: "Perencanaan dan pelaksanaan pengadaan infrastruktur teknologi, pengelolaan anggaran, manajemen aset TI, konfigurasi jaringan berbasis Mikrotik yang aman, melakukan instalasi sistem operasi dan perangkat keras.",
    project1: "Aplikasi Rhealth dirancang untuk memberikan akses mudah bagi pelanggan ke informasi obat mereka dengan menggunakan kode QR yang dihasilkan oleh administrator farmasi.",
    project2: "Rsite adalah aplikasi situs web yang dirancang untuk memperkenalkan diri saya. Dengan antarmuka pengguna modern, Anda dapat menyesuaikan warna utama, beralih antara mode terang dan gelap, dan mengubah bahasa.",
    achievement: "verifikasi",
    footer1: "Desain oleh Saya Sendiri",
    footer2: "Dibangun dengan Flutter ",
    footer3: " menggunakan Material 3 dan Provider.",
  };
}

class AppLang with ChangeNotifier {
  final FlutterLocalization _localization = FlutterLocalization.instance;
  String _countryCode = 'ID';
  String get countryCode => _countryCode;

  void changeLanguage() {
    _countryCode = (_localization.getLanguageName() == 'English') ? "EN" : "ID";
    (_localization.getLanguageName() == 'English') ? _localization.translate('id') : _localization.translate('en');
    
    notifyListeners();
  }
}